baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Lota'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"

seo:
  meta_og_title: "Lota"
  meta_og_type: "website"
  meta_og_url: "https://lota.netlify.app"
  meta_og_image: "https://raw.githubusercontent.com/vikram-ma/lota/master/screenshots/tn.png"
  meta_og_description: "Lota. We take care of software, so you can concertrate on what matters to you the most, growing your business."

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
  - jemoji
